### ISSUE TITLE
Projections error for Punters

### ISSUE THREAD

**Issue by TheMathNinja** [dfs-with-r/ffespn#20]
Getting an error for the Punter position:
`ffespn_projections(2022, 0, "P", league_id = espn_league_id_2022)`
yields 
```
Error:
! Assigned data `ratings` must be compatible with existing data.
✖ Existing data has 52 rows.
✖ Assigned data has 0 rows.
ℹ Only vectors of size 1 are recycled.
Run `rlang::last_error()` to see where the error occurred.
Warning message:
Unknown or uninitialised column: `ratings`. 
```

**Comment by zamorarr** [comment]
It looks like the data returned by ESPN does not have ratings for punters. Do you see ratings on the website? I'll just have the code return `NA` when there is no data otherwise.
