### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by gheemony** [dfs-with-r/ffespn#3]
Changing week to 1 still results in scraping of season-long projections.

**Comment by zamorarr** [comment]
Thanks for the bug issue! I think I have fixed it now. Can you try re-installing from the week1 code branch and trying again?

```R
remotes::install_github("dfs-with-r/ffespn", "week1")
library(ffespn)
ffespn_projections(2020, 1, pos = "QB")
```

**Comment by gheemony** [comment]
Appears to be working!
Does this mean that a new code branch will need to be installed each week?
Thanks!

> Thanks for the bug issue! I think I have fixed it now. Can you try re-installing from the week1 code branch and trying again?
> 
> ```r
> remotes::install_github("dfs-with-r/ffespn", "week1")
> library(ffespn)
> ffespn_projections(2020, 1, pos = "QB")
> ```

**Comment by zamorarr** [comment]
awesome. No no. Its just in a separate branch for testing to make sure I didn't break anything while "fixing" this. I'll merge this in the main branch now and you should be good to go. But obviously let me know if it stops working for week 2.

**Comment by zamorarr** [comment]
I should've mentioned that you can of course still do 

```R
ffespn_projections(2020, 0, pos = "QB")
```

and it will pull the preason projections
