### ISSUE TITLE
Week 2 bug

### ISSUE THREAD

**Issue by TheMathNinja** [dfs-with-r/ffespn#7]
I'm running this for week 2 IDP players currently and it looks like I'm getting season-long data rather than week 2.

**Comment by zamorarr** [comment]
Hey @TheMathNinja . Have you tried reinstalling the package from github? I noticed this error and made the fix a few nights ago.

**Comment by zamorarr** [comment]
It's in the main branch, I forgot to say.

```r
remotes::install_github("dfs-with-r/ffespn")
```

**Comment by TheMathNinja** [comment]
Ah thanks for this! Yes this worked, but I noticed there's a bug too. I remember saying stat_100 should be converted to def_stuffs, but it looks like something else got changed to def_stuffs. It's still showing stat_100 and another variable (which is hard to interpret) is showing as def_stuffs.

**Comment by TheMathNinja** [comment]
Also, position pos_14 = HC (Head Coach)
stat_155 / stat_174 = Team Win
stat_156 = Team Loss
stat_158 / stat_159 = Points Scored
stat_160 / stat_173 = Margin of Victory

**Comment by TheMathNinja** [comment]
slot_25 = Rookie

**Comment by zamorarr** [comment]
You did say `stat_100` for stuffs, but I mistakenly made it for `stat_110`. That is fixed now. Sorry about that. I also added in your new stats and position - thanks! You should be able to re-install the package and get all the fixes.

**Comment by TheMathNinja** [comment]
Thanks!
