### ISSUE TITLE
Merging player IDs

### ISSUE THREAD

**Issue by TheMathNinja** [dfs-with-r/ffespn#8]
I'm wondering if there's any way to include some kind of ESPN/ESPN fantasy player ID in these data frames. It would be extremely helpful for merging this data with other sources. Please let me know if this is possible!

**Comment by zamorarr** [comment]
Hey @TheMathNinja, guess I missed this one from before. Is the `id` column included in the data frame not what you were looking for? For example:

```R
df <- ffespn_projections(2021, 0, "WR")
df$id[1:10]

# [1] "4029893" "4050373" "3128724" "15795"   "2977187" "15818"  
# [7] "3042778" "15880"   "3915399" "3894912"
```

**Comment by TheMathNinja** [comment]
I'll close this one for now since I'm not sure what I meant in October. I'll keep you posted on my success with joining to other sources, haha.
